title:
  firstname: Hayden
  lastname: LeBaron
author:
  name: Hayden LeBaron
  email: hlebaron98<span>at</span>gmail<span>dot</span>com
description: > # this means to ignore newlines until "show_excerpts:"
  Copyright © 2021 Hayden LeBaron. All Rights Reserved

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: hlebaron98
    github:  HaydenLeBaron
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: hayden-lebaron-740074163
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    #gitlab:
    #- username: HaydenLeBaron
    #  instance: gitlab.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
# theme: minima

collections:
  programmingprojects:
    output: false
  otherprojects:
    output: false
  experiences:
    output: false

plugins:
 - jekyll-seo-tag
